"""
Quick Twilio Setup Script
=========================
Interactive script to help you configure Twilio credentials.
"""

import os
import sys

def print_header(text):
    """Print a formatted header"""
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60 + "\n")

def get_input(prompt, default="", validate=None):
    """Get user input with validation"""
    while True:
        if default:
            user_input = input(f"{prompt} [{default}]: ").strip()
            if not user_input:
                user_input = default
        else:
            user_input = input(f"{prompt}: ").strip()
        
        if not user_input:
            print("❌ This field is required!")
            continue
        
        if validate and not validate(user_input):
            continue
        
        return user_input

def validate_account_sid(sid):
    """Validate Twilio Account SID format"""
    if not sid.startswith("AC"):
        print("❌ Account SID must start with 'AC'")
        return False
    if len(sid) != 34:
        print("❌ Account SID should be 34 characters long")
        return False
    return True

def validate_auth_token(token):
    """Validate Twilio Auth Token format"""
    if len(token) != 32:
        print("❌ Auth Token should be 32 characters long")
        return False
    return True

def validate_phone_number(phone):
    """Validate phone number format"""
    if not phone.startswith("+"):
        print("❌ Phone number must start with '+' (e.g., +15551234567)")
        return False
    if len(phone) < 10:
        print("❌ Phone number seems too short")
        return False
    return True

def create_env_file(sid, token, phone):
    """Create or update .env file"""
    env_content = f"""# Twilio SMS Configuration
# Generated by quick_setup_twilio.py

# Your Twilio Account SID
TWILIO_ACCOUNT_SID={sid}

# Your Twilio Auth Token
TWILIO_AUTH_TOKEN={token}

# Your Twilio Phone Number (with country code)
TWILIO_PHONE_NUMBER={phone}
"""
    
    # Check if .env already exists
    if os.path.exists(".env"):
        print("\n⚠️  .env file already exists!")
        choice = input("Do you want to overwrite it? (y/n): ").lower().strip()
        if choice != 'y':
            print("Setup cancelled. Your existing .env file was not modified.")
            return False
    
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        print("\n✅ .env file created successfully!")
        return True
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        return False

def main():
    """Main setup routine"""
    print("\n🏥 " + "="*58)
    print("  Smart Clinic Token System - Twilio Quick Setup")
    print("="*61)
    
    print("""
This script will help you configure Twilio SMS credentials.

Before you start, make sure you have:
  1. Created a Twilio account at https://www.twilio.com/try-twilio
  2. Your Account SID and Auth Token from the Console
  3. A Twilio phone number

If you haven't done this yet, see TWILIO_SETUP_GUIDE.md for instructions.
    """)
    
    choice = input("Ready to proceed? (y/n): ").lower().strip()
    if choice != 'y':
        print("\nSetup cancelled. See TWILIO_SETUP_GUIDE.md for help.")
        sys.exit(0)
    
    print_header("Enter Your Twilio Credentials")
    
    # Get Account SID
    print("📋 Account SID:")
    print("   Find this in your Twilio Console Dashboard")
    print("   It starts with 'AC' and is 34 characters long")
    sid = get_input("   Enter Account SID", validate=validate_account_sid)
    
    # Get Auth Token
    print("\n🔑 Auth Token:")
    print("   Find this in your Twilio Console Dashboard")
    print("   It's a 32-character string")
    token = get_input("   Enter Auth Token", validate=validate_auth_token)
    
    # Get Phone Number
    print("\n📱 Twilio Phone Number:")
    print("   Your Twilio phone number with country code")
    print("   Examples: +15551234567 (US), +919876543210 (India)")
    phone = get_input("   Enter Phone Number", validate=validate_phone_number)
    
    # Confirm details
    print_header("Confirm Your Configuration")
    print(f"Account SID: {sid[:10]}...{sid[-4:]}")
    print(f"Auth Token:  {'*' * 28}{token[-4:]}")
    print(f"Phone Number: {phone}")
    
    confirm = input("\nIs this correct? (y/n): ").lower().strip()
    if confirm != 'y':
        print("\nSetup cancelled. Please run the script again.")
        sys.exit(0)
    
    # Create .env file
    if create_env_file(sid, token, phone):
        print_header("✅ Setup Complete!")
        print("""
Next steps:

1. Test your configuration:
   python diagnose_twilio.py

2. Restart the application to load the new credentials:
   python main.py

3. Test SMS by registering a patient:
   - Go to: http://localhost:8000/reception
   - Register with a verified phone number
   - Check if SMS is received

Note: For Twilio trial accounts, you can only send SMS to verified numbers.
Verify numbers at: https://console.twilio.com/phone-numbers/verified

📚 For more help, see: TWILIO_SETUP_GUIDE.md
        """)
    else:
        print("\nSetup failed. Please try again or manually create .env file.")
        sys.exit(1)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(0)
